export function slicesFor(rect, width, height, overlap) {
    const positions = (length, span) => {
        if (length <= span) return [0];
        const count = Math.ceil((length - span) / (span - overlap)) + 1;
        return Array.from({ length: count }, (_, i) => Math.round(i * (length - span) / (count - 1)));
    };
    return positions(rect.height, height).flatMap((y, row) => positions(rect.width, width).map((x, column) => ({ id: `R${row + 1}-C${column + 1}`, row: row + 1, column: column + 1, x: rect.x + x, y: rect.y + y, width: Math.min(width, rect.width), height: Math.min(height, rect.height) })));
}
const escape = text => String(text).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

export function printBooklet(meta, images, paper) {
    const label = `${meta.name}${meta.story ? '' : ` - ${meta.difficulty}`} - ${meta.graphics}`;
    const pageWidth = paper === 'a4' ? '297mm' : '11in', pageHeight = paper === 'a4' ? '210mm' : '8.5in';
    const pages = images.pages ?? [{ id: 'Overview', rect: meta.region, image: images.overview }, ...meta.slices.map((s, i) => ({ id: s.id, rect: s, image: images.sheets[i] }))];
    return `<!doctype html><html><head><meta charset="utf-8"><title>${escape(label)} - drawing pack</title><style>
    @page{size:${pageWidth} ${pageHeight};margin:0}*{box-sizing:border-box}body{margin:0;background:#dce2e5;font:12px Arial,sans-serif;color:#253943}.page{width:${pageWidth};height:${pageHeight};padding:.35in .45in;background:white;break-after:page;display:flex;flex-direction:column;gap:8px;overflow:hidden}.page:last-child{break-after:auto}header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #668579;padding-bottom:8px}h1{font-size:20px;margin:0 0 5px}p{margin:4px 0}.code{font-size:21px;font-weight:bold;text-align:right}.sub{font-size:11px;color:#53666c}.map{height:4.8in;flex-shrink:0;border:1px solid #a6b3b5;display:flex;align-items:center;justify-content:center;background:white}.map img{max-width:100%;max-height:100%;object-fit:contain}.notes{flex:1;min-height:.7in;background:repeating-linear-gradient(white 0,white 23px,#dde2e3 23px,#dde2e3 24px);padding-top:4px}footer{display:flex;justify-content:space-between;font-size:10px;color:#57676e}.guide{font-size:12px}.toolbar{padding:18px;text-align:center}.toolbar label{display:inline-block;margin:6px}.page.omit{display:none}.toolbar button{padding:10px 20px}@media print{body{background:white}.toolbar{display:none}}@media screen{.page{margin:16px auto;box-shadow:0 2px 12px #4563}}
    </style></head><body><div class="toolbar"><button onclick="window.print()">Print drawing pack</button><p>Print landscape at 100% / actual size. Turn off browser headers and footers. You can also choose Save as PDF.</p><div>${pages.map((page, i) => `<label><input type="checkbox" checked onchange="document.querySelectorAll('.page')[${i}].classList.toggle('omit', !this.checked)"> ${escape(page.id)}</label>`).join('')}</div></div>${pages.map((page, i) => `<section class="page"><header><div><h1>${escape(label)}</h1><div class="sub">Level ${meta.level}${meta.level === 15 ? ` / ${escape(meta.floor)}` : ''} | ${escape(meta.packId)} | revision ${escape(meta.revision.short)}${meta.revision.dirty ? ' + local edits' : ''}</div></div><div class="code">${escape(page.id)}<p class="sub">Page ${i + 1} of ${pages.length}</p></div></header><p class="sub">${page.caption ? escape(page.caption) : `World X ${page.rect.x} to ${page.rect.x + page.rect.width} | Y ${page.rect.y} to ${page.rect.y + page.rect.height} | grid = 100 game pixels`}</p><div class="map"><img src="data:image/png;base64,${page.image}" alt="${escape(label)} ${escape(page.id)}"></div><p class="guide">${page.caption ? 'Draw changes to the scene or dialogue. Use arrows and notes to describe what should happen.' : i === 0 ? 'Start with this map, then use the numbered close-ups. Draw new platforms, circle changes, or cross things out. Neighboring sheets overlap.' : 'Draw on the picture. Add arrows and notes here: what should happen, and what should Onyx do?'}</p><div class="notes">Name: ____________________ &nbsp; My idea: __________________________________________________________</div><footer><span>Keep the page code visible when you photograph or scan your drawing.</span><span>${page.caption ? 'Storyboard still; animation shown in one pose.' : 'Static layout; moving hazards shown in one pose.'}</span></footer></section>`).join('')}</body></html>`;
}

export const NAMES = ['The Pound', 'Pound Escape', 'Dark Forest', 'The Beach', 'The Mountains', 'Ski Slopes', 'The Chase', 'Underwater Reef', 'Stormy Pier', 'Construction Site', 'Neon Metropolis', 'The Warm Bakery', 'Market Day', 'The Backyard', 'Home', 'Custom Course'];
